apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-client
  template:
    metadata:
      labels:
        app: app-client
    spec:
      containers:
        - name: app-client
          image: /app-client
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-client-service
spec:
  type: ClusterIP
  selector:
    app: app-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
